export const FETCH_SELECTED_COMPANY = 'FETCH_SELECTED_COMPANY';
export const FETCH_SELECTED_COMPANY_ERROR = 'FETCH_SELECTED_COMPANY_ERROR';
export const FETCH_SELECTED_COMPANY_SUCCESS = 'FETCH_SELECTED_COMPANY_SUCCESS';
export const FETCH_SELECTED_COMPANY_TYPES = [
    FETCH_SELECTED_COMPANY,
    FETCH_SELECTED_COMPANY_SUCCESS,
    FETCH_SELECTED_COMPANY_ERROR
];