// Companies
export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANIES_FULFILLED = 'FETCH_COMPANIES_FULFILLED';

export const FETCH_COMPANY = 'FETCH_COMPANY';
export const FETCH_COMPANY_FULFILLED = 'FETCH_COMPANY_FULFILLED';

// Members
export const FETCH_MEMBERS = 'FETCH_MEMBERS';

// Locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';