export const FETCH_COMPANY = 'FETCH_COMPANY';
export const FETCH_COMPANY_ERROR = 'FETCH_COMPANY_ERROR';
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const FETCH_COMPANY_TYPES = [
    FETCH_COMPANY,
    FETCH_COMPANY_SUCCESS,
    FETCH_COMPANY_ERROR
];

export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANIES_ERROR = 'FETCH_COMPANIES_ERROR';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_TYPES = [
    FETCH_COMPANIES,
    FETCH_COMPANIES_SUCCESS,
    FETCH_COMPANIES_ERROR
];